# Generated by Django 3.2 on 2023-08-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcioncotizacionconsultoria',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='descripcioncotizacionmanodeobra',
            name='disponibilidad',
        ),
    ]
