# Generated by Django 3.2 on 2023-08-07 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20230804_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezasrepuesto',
            name='tipo_moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.moneda'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='tipo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
