# Generated by Django 3.2 on 2023-08-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20230806_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='manodeobra',
            name='tipo_moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.moneda'),
        ),
    ]
