# Generated by Django 3.2 on 2023-08-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_manodeobra_tipo_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezasrepuesto',
            name='peso',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
