# Generated by Django 3.2 on 2023-08-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20230807_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='observacion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cotizacionconsultoria',
            name='observacion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cotizacionmanodeobra',
            name='observacion',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
